name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - if: matrix.python-version == '3.9' && runner.os == 'Linux'
      name: Lint
      run: |
        pip install "black==22.10.0" "mypy>=0.991" "ruff>=0.0.166"
        ruff check .
        black --check --diff .
        mypy --install-types --non-interactive earningscall tests

    - name: Run tests and track code coverage
      run: |
        pip install -e . "coverage[toml]>=6.5" pytest responses coveralls
        python -m coverage run -m pytest tests
        python -m coverage combine
        python -m coverage report --show-missing
    - if: matrix.python-version == '3.9' && runner.os == 'Linux'
      name: Publish Coverage to Coveralls
      run: python -m coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  run-container-matrix:
    name: Container matrix on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Hatch
      run: pip install --upgrade "hatch<1.16" hatch-containers

    - name: Run tests in container matrix
      run: hatch run all:test
